Keras: The high-level API for TensorFlow 


In [31]:
import tensorflow as tf
import keras
from keras import layers
from keras.models import Sequential

Keras Layers

In [43]:
layer1 = layers.Dense(10, activation="relu", name="hidden1")
layer2 = layers.Dense(64, activation="sigmoid", name = "hidden2")
layer3 = layers.Dense(4, name = "output")
x = tf.ones([1000,3])
output = layer3(layer2(layer1(x)))
print(output)

tf.Tensor(
[[-0.54091126  0.08168858  1.0390706   0.31065363]
 [-0.54091126  0.08168858  1.0390706   0.31065363]
 [-0.54091126  0.08168858  1.0390706   0.31065363]
 ...
 [-0.54091126  0.08168858  1.0390706   0.31065363]
 [-0.54091126  0.08168858  1.0390706   0.31065363]
 [-0.54091126  0.08168858  1.0390706   0.31065363]], shape=(1000, 4), dtype=float32)


The Sequential model 

In [44]:
model = Sequential()
model.add(layer1)
model.add(layer2)
model.add(layer3)
model(x)
model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden1 (Dense)             (1000, 10)                40        
                                                                 
 hidden2 (Dense)             (1000, 64)                704       
                                                                 
 output (Dense)              (1000, 4)                 260       
                                                                 
Total params: 1,004
Trainable params: 1,004
Non-trainable params: 0
_________________________________________________________________


In [53]:
model = Sequential(
    [
        layers.Input(4,),
        layers.Dense(8,activation="relu", name = "layer1"),
        layers.Dense(64, activation="relu", name= "layer2"),
        layers.Dense(10, activation="softmax", name= "output")
    ]
)
print(model.summary())

Model: "sequential_18"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 8)                 40        
                                                                 
 layer2 (Dense)              (None, 64)                576       
                                                                 
 output (Dense)              (None, 10)                650       
                                                                 
Total params: 1,266
Trainable params: 1,266
Non-trainable params: 0
_________________________________________________________________
None


Functional API

In [67]:
input = layers.Input(shape=(100,))
layer1 = layers.Dense(10, activation="relu", name = "layer1")(input)
layer2 = layers.Dense(20, activation="relu", name = "layer2")(layer1)
layer3 = layers.Dense(30, activation="relu", name = "layer3")(input)

In [ ]:
input = layers.Input(shape=(100,))
x = layers.Dense(10, activation="relu", name = "layer1")(input)
x =layers.Dense(20, activation="relu", name = "layer2")(x)
x = layers.Dense(15, activation="relu", name = "layer3")(x)

output1 = layers.Dense(40, activation="relu", name = "output1")(x)
output2 = layers.Dense(50, activation="relu", name = "output2")(x)