In [96]:
import tensorflow as tf
import keras
from keras import layers
from keras.datasets import mnist
from keras.models import Sequential
from sklearn.preprocessing import OneHotEncoder

Data collection and Preprocessing

In [97]:
(X_train, y_train), (X_test, y_test)= mnist.load_data()
X_train = X_train.reshape(-1, 28 * 28).astype("float16") / 255
X_test = X_test.reshape(-1,28*28).astype("float16") / 255
X_train.shape

(60000, 784)

In [98]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

Model architecture

In [99]:
model = Sequential(
    [
        layers.Dense(150, activation="relu", input_shape = (28 * 28,),name= "layer1"),
        layers.Dense(256, activation="relu", name = "layer2"),
        layers.Dense(10,name = "output")
    ]
)
model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 150)               117750    
                                                                 
 layer2 (Dense)              (None, 256)               38656     
                                                                 
 output (Dense)              (None, 10)                2570      
                                                                 
Total params: 158,976
Trainable params: 158,976
Non-trainable params: 0
_________________________________________________________________


Model compilation

In [100]:
model.compile(
    optimizer= tf.keras.optimizers.RMSprop(),
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics= ["accuracy"]
)
model.fit(X_train, y_train, batch_size=32, epochs = 1)

1875/1875 [==============================] - 16s 8ms/step - loss: 0.2177 - accuracy: 0.9356


Model Evaluation and prediction

In [101]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 2s 6ms/step - loss: 0.1401 - accuracy: 0.9586


[0.1400938183069229, 0.9585999846458435]

In [102]:
model.predict(tf.nn.softmax(X_test[0:1]))

1/1 [==============================] - 0s 106ms/step


array([[-0.5486419 , -0.3516749 , -0.36595914, -0.31087163, -0.3084245 ,
         0.30750903, -0.41437733, -0.13392949, -0.469052  , -0.42145592]],
      dtype=float32)

In [148]:
predictions = tf.argmax(model.predict(X_test),axis = 1)
predictions

313/313 [==============================] - 1s 3ms/step


<tf.Tensor: shape=(10000,), dtype=int64, numpy=array([7, 2, 1, ..., 4, 5, 6], dtype=int64)>

In [144]:
c = tf.constant([[1,6],
                 [9,2],
                 [6,20]])
print(c.shape)
print(tf.argmax(c, axis =0))

(3, 2)
tf.Tensor([1 2], shape=(2,), dtype=int64)


In [146]:
model.predict(X_test).shape

313/313 [==============================] - 1s 3ms/step


(10000, 10)