In [1]:
import tensorflow as tf
import keras
from keras import layers
from keras.datasets import mnist
from keras.models import Sequential
from sklearn.preprocessing import OneHotEncoder

Data collection and Preprocessing

In [2]:
(X_train, y_train), (X_test, y_test)= mnist.load_data()
X_train = X_train.reshape(-1, 28 * 28).astype("float16") / 255
X_test = X_test.reshape(-1,28*28).astype("float16") / 255
X_train.shape

(60000, 784)

In [3]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

Model architecture

In [4]:
model = Sequential(
    [
        layers.Dense(150, activation="relu", input_shape = (28 * 28,),name= "layer1"),
        layers.Dense(256, activation="relu", name = "layer2"),
        layers.Dense(10,name = "output")
    ]
)
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 150)               117750    
                                                                 
 layer2 (Dense)              (None, 256)               38656     
                                                                 
 output (Dense)              (None, 10)                2570      
                                                                 
Total params: 158,976
Trainable params: 158,976
Non-trainable params: 0
_________________________________________________________________


Model compilation

In [5]:
model.compile(
    optimizer= tf.keras.optimizers.RMSprop(),
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics= ["accuracy"]
)
model.fit(X_train, y_train, batch_size=32, epochs = 1)

1875/1875 [==============================] - 14s 7ms/step - loss: 0.2167 - accuracy: 0.9352


Model Evaluation and prediction

In [6]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 2s 4ms/step - loss: 0.1153 - accuracy: 0.9646


[0.1152627095580101, 0.9646000266075134]

In [7]:
tf.nn.softmax(model.predict((X_test[0:1])))

1/1 [==============================] - 0s 136ms/step


<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[1.31832634e-09, 6.48288534e-08, 9.14514203e-06, 5.45519197e-06,
        5.29059088e-12, 2.19911627e-08, 3.32052772e-14, 9.99985218e-01,
        2.66671307e-08, 1.09966315e-07]], dtype=float32)>

In [8]:
predictions = tf.argmax(model.predict(X_test),axis = 1)
predictions

313/313 [==============================] - 1s 2ms/step


<tf.Tensor: shape=(10000,), dtype=int64, numpy=array([7, 2, 1, ..., 4, 5, 6], dtype=int64)>

In [9]:
c = tf.constant([[1,6],
                 [9,2],
                 [6,20]])
print(c.shape)
print(tf.argmax(c, axis =0))

(3, 2)
tf.Tensor([1 2], shape=(2,), dtype=int64)


In [10]:
model.predict(X_test).shape

313/313 [==============================] - 1s 3ms/step


(10000, 10)