Tensorflow 2

In [40]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.10.0'

Tensor Basics

In [17]:
my_tensor = tf.constant([1,2.5,3], dtype=tf.float64, shape=(1,3))
print(my_tensor)

tf.Tensor([[1.  2.5 3. ]], shape=(1, 3), dtype=float64)


In [34]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[4,5],[6,7]])
print(a)
print(b)
print(tf.add(a,b))
print(tf.subtract(a,b))
print(tf.multiply(a,b))
print(tf.matmul(a,b))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[4 5]
 [6 7]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5  7]
 [ 9 11]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-3 -3]
 [-3 -3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 4 10]
 [18 28]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[16 19]
 [36 43]], shape=(2, 2), dtype=int32)


In [43]:
x = np.array([[1,2],
              [3,4]])
y = np.array([[4,5],
              [6,7]])
print(x @ y)

[[16 19]
 [36 43]]


In [46]:
print(a +b)
print(a -b)
print(a* b)
print(a @ b)
print(a.numpy())

tf.Tensor(
[[ 5  7]
 [ 9 11]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-3 -3]
 [-3 -3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 4 10]
 [18 28]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[16 19]
 [36 43]], shape=(2, 2), dtype=int32)
[[1 2]
 [3 4]]


In [107]:
c = tf.constant([[5,6],
                 [9,3],
                 [19,3]], shape=(3,2,1))
print(c)

tf.Tensor(
[[[ 5]
  [ 6]]

 [[ 9]
  [ 3]]

 [[19]
  [ 3]]], shape=(3, 2, 1), dtype=int32)


In [100]:
d = tf.Variable([1,2,3], name="my variable")
d[0].assign(10)
print(d)

<tf.Variable 'my variable:0' shape=(3,) dtype=int32, numpy=array([10,  2,  3])>


Tensor shapes

In [117]:
c = tf.constant([[1,6],
                 [8,3],
                 [9,4]])
z = tf.reshape(c, [-1,1])
print(c)
print(z)

tf.Tensor(
[[1 6]
 [8 3]
 [9 4]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1]
 [6]
 [8]
 [3]
 [9]
 [4]], shape=(6, 1), dtype=int32)


In [111]:
print(z.ndim)
print(tf.rank(z))

3
tf.Tensor(3, shape=(), dtype=int32)


Tensor indexing

In [131]:
a = tf.constant([4,6,9,8,5,2,1])
print(a[::-1])

tf.Tensor([1 2 5 8 9 6 4], shape=(7,), dtype=int32)


In [140]:
c = tf.constant([[6,5],
                 [9,3],
                 [4,2]])
print(c[0:2,1:])

tf.Tensor(
[[5]
 [3]], shape=(2, 1), dtype=int32)


In [137]:
x = [[1,2],
     [3,4]]
x = np.array(x)
print(x[0,1])

2


Broadcasting

In [141]:
a = tf.constant([1,2,3])

print(a + 2)

tf.Tensor([3 4 5], shape=(3,), dtype=int32)


In [154]:
x = tf.constant([1,2,3], shape=(3,1))
y = tf.constant([1,2,3,4], shape=(1,4))
print(x)
print(y)
print(x + y)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]], shape=(3, 4), dtype=int32)


In [148]:
y_stretch = tf.constant([[1,2,3,4],
                         [1,2,3,4],
                         [1,2,3,4]])
x_stretch = tf.constant([[1,1,1,1],
                         [2,2,2,2],
                         [3,3,3,3]])
print(x_stretch)
print(y_stretch)
print(x_stretch + y_stretch)

tf.Tensor(
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]], shape=(3, 4), dtype=int32)


Ragged Tensors

In [173]:
x = tf.ragged.constant([[1,2,3],
                        [4,5]])
print(x.shape)

(2, None)


Sparse Tensors

In [184]:
from sklearn.preprocessing import OneHotEncoder

x = np.array([0,1,1,2,0]).reshape(-1,1)
encoder = OneHotEncoder(sparse_output=False)
x = encoder.fit_transform(x)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [194]:
x = tf.sparse.SparseTensor(indices=[[0,2], [3, 1]], values=[5,3], dense_shape=[4,3])
print(x)
print(tf.sparse.to_dense(x))

SparseTensor(indices=tf.Tensor(
[[0 2]
 [3 1]], shape=(2, 2), dtype=int64), values=tf.Tensor([5 3], shape=(2,), dtype=int32), dense_shape=tf.Tensor([4 3], shape=(2,), dtype=int64))
tf.Tensor(
[[0 0 5]
 [0 0 0]
 [0 0 0]
 [0 3 0]], shape=(4, 3), dtype=int32)
